---
title: Bio4158/Bio5158 - Report 1
subtitle: Exercise
author: "Group 22 - Nalan Kurnaz"
date: today
format:
  html:
    embed-resources: true
    toc: true
    code-fold: show
    code-tools: true
---


# Task


For each of the following cases, list:

1. The ‘biological’ (i.e. ‘scientific’) hypothesis/hypotheses that might be tested with the data. Remember, a biological hypothesis is a proposed cause for a given observation/pattern (i.e. the pattern described in the case study). Focus on the information provided in the case description. 
2. The prediction for each biological hypothesis you propose. This is the pattern you expect to see in the results, given the study that was performed, IF THIS BIOLOGICAL HYPOTHESIS IS TRUE.
2. The statistical null hypothesis associated with each of your biological hypotheses (this is all others patterns in the results except that predicted by your biological hypothesis).
2. If present, any descriptive elements (i.e. variables for which you are interested in describing their effects) and the statistical null hypothesis associated with each (this is normally the absence of any pattern – i.e. no association between the variable of interest and your response variable). If there are no descriptive elements, then state so.
2. The dependent variable
2. The independent variables 
2. the statistical model in verbal form  

Overall grading on 42 (14 points per case, 2 points per question).

## Example

In studies of bottom dwelling (benthic) invertebrates, sieves are generally used to eliminate unwanted fine particles and to facilitate sorting of organisms. Different sieves have been observed to vary in the efficiency with which they retain individuals of different species (possibly due to variation in organism size/shape). In a study completed in Dr. Morin’s laboratory, they processed a similar number of individuals of each of 30 species and recorded the total number of individuals of each species that were retained by the sieve. They also recorded the average size and leg length of individuals of each species. Three different students repeated this experiment as they were also interested in knowing whether these students differed in their overall efficiency.

1. **Possible ‘biological’ hypotheses**: H1: The efficiency of the sieve varies among species because those species with larger average size are more easily retained by the sieve. H2: The efficiency of the sieve varies among species because species with longer average legs are more likely to get caught in the sieve. 
1. **Predictions**: H1: The number retained will increase with increasing average size; H2: The number of retained individuals will increase with increasing leg length.
1. **Statistical null hypotheses**: H1: The number of retained individuals will decrease or not change with increasing average size; H2: The number of retained individuals decreases or not change with increasing leg length.
1. **Descriptive elements**: Student is a descriptive variable as there is no associated biological hypothesis; they simply want to know if these three differ in how efficiently they sort. The statistical null hypothesis is that the number of retained individuals does not differ among these three students. 
1. **Dependent variable**: the number of individuals retained for each of the 30 species.
1. **Independent variables**: average size of each of the 30 species, average leg length of each of the 30 species, and student identity.
1. **Statistical model**: number retained = average size + average leg length + student identity + error



## Case 1.

Amphibians are declining worldwide. Endocrine disruptors have been suggested as one of the possible causes as there is reason to think that they may slow development. Valerie Langlois (Trudeau lab) has studied the effect of atrazine (the most commonly used herbicide in corn and soy fields) on the development of the common frog, Rana pipiens. Fertilized frog eggs were randomly assigned to different exposure treatments (control and several concentrations of atrazine) and the age at which each individual went through metamorphosis was recorded along with the sex of the individual.

### Answers

1. **Possible 'biological' hypothesis**: H1: Exposure to atrazine changes developmental timing in Rana pipiens, such that individuals exposed to higher concentrations take longer to reach metamorphosis. H2: Exposure to atrazine changes sexual differentiation in Rana pipiens, causing changes in the proportion of males and females.

2. **Predictions**: H1: The age at metamorphosis will increase with higher atrazine concentration.; H2: The sex ratio will shift more with higher atrazine concentration.

3. **Statistical null hypothesis**: H1: Atrazine concentration has no effect on the age at metamorphosis. H2: Atrazine concentration has no effect on the proportion of males and females in Rana pipiens.

4. **Descriptive elements**: There are no descriptive elements in this study since all measured variables are tied to biological hypothesis.

5. **Dependent Variable**: Depending on the hypothesis, either age at metamorphosis or sex ratio are dependent variable.

6. **Independent Variable**: Atrazine concentration (control and several treatment levels) is the independent variable.

7. **Statistical Model**: Effect of Atrazine = Atrazine Concentrations + Age at Metamorphosis + Sex + Error 


## Case 2

The majority of water loss in insects occurs across the cuticle and cuticular permeability to water can therefore have important implications on the ability to tolerate desiccation stress. Insect cuticles are covered in a waxy layer of hydrocarbons, the amount of which may affect cuticular permeability. Water loss also occurs when insects ‘breathe’, which they do through valved openings (spiracles) in their cuticle. Spiracles opening increases in frequency and/or duration with increasing locomotor activity to facilitate gas exchange, thereby increasing water loss as well. In Drosophila serrata, rates of water loss have been observed to vary substantially among individuals even when measured under the same (and constant) environmental conditions. In a recent study, a student measured water loss of individual D. serrata under constant environmental conditions. They also recorded the locomotor activity of each individual during the measurement (total distance moved), then immediately following this they extracted and quantified the amount of 2-MeC~26~, the most abundant cuticular hydrocarbon in this species.

### Answers

1. **Possible 'biological' Hypothesis**: H1: Rates of water loss vary among individuals because those with greater amounts of 2-MeC26 are more resistant to cuticular water loss. H2: Rates of water loss vary among individuals because those with higher locomotor activity experience more respiratory water loss.   

2. **Predictions**: H1: Water loss will decrease with higher amounts of 2-MeC26. H2: Water loss will increase with increasing locomotor activity.

3. **Statistical Null Hypothesis**: H1: Having 2-MeC26 will have no effect on the rates of water loss. H2: Locomotor activity will have no effect in the rates of water loss.

4. **Descriptive elements**: There is no descriptive element since all measured variables are tied to the biological hypothesis.

5. **Dependent variable**: Rate of water loss

6. **Independent variable**: Amount of 2-MeC26 and locomotor activity

7. **Statistical Model**: Water Loss = Amount of 2-MeC26 + locomotor activity + error



## Case 3

A graduate student in the Rundle lab observed substantial variation in mating success among a group of males from a population of Drosophila melanogaster, with multiple females appearing to accept or reject particular males repeatedly during courtship. In a recent study they recorded the mating success of males that were randomly assigned to one of two different perfuming treatments (perfumed with a pheromone extract obtained from separate males known to have either unusually high or unusually low mating success). They also recorded the weight of each male and the amount of blue colouring on their wings because they were curious as to whether these traits might be associated with mating success. 



### Answers

1. **Possible 'biological' Hypothesis**: H1: The mating success of males varies with perfuming treatment such that males perfumed with pheromones from high mating success males have higher mating success than those perfumed with pheromones from low mating success males. H2: The mating success of males varies with their physical characteristics, specifically body weight and the amount of blue wing coloration, with heavier males or males with more blue coloration having higher mating success.

2. **Predictions**: H1: Males perfumed with high mating success pheromones will have higher mating success than those perfumed with low mating success pheromones. H2: Mating success will increase with body weight and greater blue wing coloration. 

3. **Statistical Null Hypothesis**: H1: Perfuming treatment has no effect on mating success, and males perfumed with high or low mating success pheromones have equal mating success. H2: Male body weight and wing coloration have no effect on mating success.

4. **Descriptive elements**: There are no descriptive elements as there is no variable outside of hypothesis. 

5. **Dependent variable**: Mating success is dependent variable. 

6. **Independent variable**: Perfuming treatments and physical characteristics (the amount of blue wing coloration, body weight) are independent variables.

7. **Statistical Model**: Mating Success = perfuming treatment + body weight + wing coloration + error

